// react/src/components/RadioButtonTileGroup.tsx
import { useCallback, useId, useRef } from 'react';
import type { KeyboardEvent } from 'react';
import { RadioButtonTile } from './RadioButtonTile';
import type { RadioCardOption } from './RadioCardGroup';

export interface RadioButtonTileGroupProps {
  title: string;
  options: RadioCardOption[];
  value: string | null;
  onChange: (value: string) => void;
  name?: string;
}

/** Group of Button-Tile-based radio options. Same a11y model as RadioCardGroup. */
export function RadioButtonTileGroup({
  title,
  options,
  value,
  onChange,
  name,
}: RadioButtonTileGroupProps) {
  const fallbackName = useId();
  const groupName = name ?? fallbackName;
  const refs = useRef<Array<HTMLButtonElement | null>>([]);

  const handleSelect = useCallback((v: string) => onChange(v), [onChange]);

  const handleNav = useCallback(
    (idx: number) => (e: KeyboardEvent<HTMLButtonElement>) => {
      let next = -1;
      if (e.key === 'ArrowDown' || e.key === 'ArrowRight') next = (idx + 1) % options.length;
      if (e.key === 'ArrowUp' || e.key === 'ArrowLeft')
        next = (idx - 1 + options.length) % options.length;
      if (next >= 0) {
        e.preventDefault();
        refs.current[next]?.focus();
        onChange(options[next].value);
      }
    },
    [onChange, options],
  );

  const firstEnabledIdx = options.findIndex((o) => !o.disabled);

  return (
    <div role="radiogroup" aria-label={title} className="rbt-group">
      <p className="rbt-group__title">{title}</p>
      <div className="rbt-group__grid">
        {options.map((opt, idx) => {
          const isSelected = opt.value === value;
          const isFirst = idx === firstEnabledIdx;
          const isInTabOrder = isSelected || (value === null && isFirst);
          return (
            <RadioButtonTile
              key={opt.value}
              ref={(el) => {
                refs.current[idx] = el;
              }}
              name={groupName}
              value={opt.value}
              label={opt.label}
              checked={isSelected}
              disabled={opt.disabled}
              tabIndex={isInTabOrder ? 0 : -1}
              onSelect={handleSelect}
              onKeyboardNav={handleNav(idx)}
            />
          );
        })}
      </div>
    </div>
  );
}

// angular/src/app/radio-button-tile-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  HostBinding,
  Input,
  Output,
  QueryList,
  ViewChildren,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RadioButtonTileComponent } from './radio-button-tile.component';
import type { RadioCardOption } from './radio-card-group.component';

@Component({
  selector: 'app-radio-button-tile-group',
  standalone: true,
  imports: [CommonModule, RadioButtonTileComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <p class="rbt-group__title">{{ title }}</p>
    <div class="rbt-group__grid">
      <button
        appRadioButtonTile
        *ngFor="let opt of options; let i = index; trackBy: trackByValue"
        [label]="opt.label"
        [value]="opt.value"
        [checked]="opt.value === value"
        [disabled]="!!opt.disabled"
        [tabIndexValue]="isInTabOrder(opt, i) ? 0 : -1"
        (selectValue)="onSelect($event)"
        (navigate)="onNavigate($event, i)"
      ></button>
    </div>
  `,
})
export class RadioButtonTileGroupComponent {
  @Input({ required: true }) title!: string;
  @Input({ required: true }) options: RadioCardOption[] = [];
  @Input() value: string | null = null;

  @Output() valueChange = new EventEmitter<string>();

  @ViewChildren(RadioButtonTileComponent) tiles!: QueryList<RadioButtonTileComponent>;

  @HostBinding('class.rbt-group') readonly base = true;
  @HostBinding('attr.role') readonly role = 'radiogroup';
  @HostBinding('attr.aria-label') get ariaLabel() {
    return this.title;
  }

  isInTabOrder(opt: RadioCardOption, idx: number): boolean {
    if (this.value !== null) return opt.value === this.value;
    return idx === this.options.findIndex((o) => !o.disabled);
  }

  onSelect(value: string): void {
    this.value = value;
    this.valueChange.emit(value);
  }

  onNavigate(event: KeyboardEvent, idx: number): void {
    let next = -1;
    if (event.key === 'ArrowDown' || event.key === 'ArrowRight')
      next = (idx + 1) % this.options.length;
    if (event.key === 'ArrowUp' || event.key === 'ArrowLeft')
      next = (idx - 1 + this.options.length) % this.options.length;
    if (next >= 0) {
      event.preventDefault();
      this.tiles.toArray()[next]?.focus();
      this.onSelect(this.options[next].value);
    }
  }

  trackByValue(_: number, opt: RadioCardOption) {
    return opt.value;
  }
}
