// angular/src/app/radio-button-tile.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostBinding,
  HostListener,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Button Tile-based Radio Card. Renders as a <button appButtonTile> with
 * radio semantics. Visual states (hover, pressed, focused, selected) come
 * from the .atlas-button-tile + .rbt-tile / .is-selected CSS chain.
 */
@Component({
  selector: 'button[appRadioButtonTile]',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <span class="rbt-content">
      <span class="rbt-radio" aria-hidden="true"></span>
      <span class="rbt-label">{{ label }}</span>
    </span>
  `,
})
export class RadioButtonTileComponent {
  @Input({ required: true }) label!: string;
  @Input({ required: true }) value!: string;
  @Input() checked = false;
  @Input() disabled = false;
  @Input() tabIndexValue = -1;

  @Output() selectValue = new EventEmitter<string>();
  @Output() navigate = new EventEmitter<KeyboardEvent>();

  constructor(private readonly host: ElementRef<HTMLElement>) {}

  focus() {
    this.host.nativeElement.focus();
  }

  @HostBinding('class.atlas-button-tile') readonly base = true;
  @HostBinding('class.rbt-tile') readonly tileClass = true;
  @HostBinding('class.is-selected') get selectedClass() {
    return this.checked;
  }
  @HostBinding('class.is-disabled') get disabledClass() {
    return this.disabled;
  }
  @HostBinding('attr.type') readonly buttonType = 'button';
  @HostBinding('attr.role') readonly role = 'radio';
  @HostBinding('attr.aria-checked') get ariaChecked() {
    return this.checked;
  }
  @HostBinding('attr.aria-disabled') get ariaDisabled() {
    return this.disabled ? 'true' : null;
  }
  @HostBinding('attr.tabindex') get tabIndex() {
    return this.disabled ? -1 : this.tabIndexValue;
  }
  @HostBinding('attr.disabled') get disabledAttr() {
    return this.disabled ? '' : null;
  }
  @HostBinding('attr.data-value') get dataValue() {
    return this.value;
  }

  @HostListener('click') onClick() {
    if (this.disabled) return;
    this.selectValue.emit(this.value);
  }

  @HostListener('keydown', ['$event']) onKeydown(event: KeyboardEvent) {
    if (this.disabled) return;
    if (event.key === ' ' || event.key === 'Enter') {
      event.preventDefault();
      this.selectValue.emit(this.value);
      return;
    }
    this.navigate.emit(event);
  }
}

// react/src/components/RadioButtonTile.tsx
import { forwardRef } from 'react';
import type { KeyboardEvent } from 'react';
import { ButtonTile } from '../primitives/ButtonTile';

export interface RadioButtonTileProps {
  label: string;
  value: string;
  checked: boolean;
  disabled?: boolean;
  name?: string;
  onSelect?: (value: string) => void;
  onKeyboardNav?: (event: KeyboardEvent<HTMLButtonElement>) => void;
  tabIndex?: number;
}

/**
 * Button Tile-based Radio Card. Wraps the Atlas Button Tile primitive with
 * radio role and group navigation semantics. Visual states (hover, pressed,
 * focused, selected) come from the tile primitive's CSS plus the `is-selected`
 * modifier.
 */
export const RadioButtonTile = forwardRef<HTMLButtonElement, RadioButtonTileProps>(
  function RadioButtonTile(
    { label, value, checked, disabled, name, onSelect, onKeyboardNav, tabIndex },
    ref,
  ) {
    const classes = [
      'rbt-tile',
      checked ? 'is-selected' : '',
      disabled ? 'is-disabled' : '',
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <ButtonTile
        ref={ref}
        role="radio"
        aria-checked={checked}
        aria-disabled={disabled || undefined}
        tabIndex={disabled ? -1 : tabIndex ?? (checked ? 0 : -1)}
        data-name={name}
        data-value={value}
        disabled={disabled}
        className={classes}
        onClick={() => !disabled && onSelect?.(value)}
        onKeyDown={(e) => {
          if (disabled) return;
          if (e.key === ' ' || e.key === 'Enter') {
            e.preventDefault();
            onSelect?.(value);
            return;
          }
          onKeyboardNav?.(e);
        }}
      >
        <div className="rbt-content">
          <span className="rbt-radio" aria-hidden="true" />
          <span className="rbt-label">{label}</span>
        </div>
      </ButtonTile>
    );
  },
);
